// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvcjpjcMhtZ00pTyHTBsu1Q2p3mD_WZ6E',
    appId: '1:11162248886:web:63aec502aa0bc45dbce817',
    messagingSenderId: '11162248886',
    projectId: 'fluuter-1aadd',
    authDomain: 'fluuter-1aadd.firebaseapp.com',
    storageBucket: 'fluuter-1aadd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDetgfpnSAAXUL4r9RuFhc8UM0JxH8I_aU',
    appId: '1:11162248886:android:cf04112350d16f65bce817',
    messagingSenderId: '11162248886',
    projectId: 'fluuter-1aadd',
    storageBucket: 'fluuter-1aadd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASmVs-MW45q2ID2cfxNfazU8coesRFO_4',
    appId: '1:11162248886:ios:1097890109577878bce817',
    messagingSenderId: '11162248886',
    projectId: 'fluuter-1aadd',
    storageBucket: 'fluuter-1aadd.appspot.com',
    androidClientId: '11162248886-1lsegm6ijjlj723r38upo42fr4bqsvl8.apps.googleusercontent.com',
    iosClientId: '11162248886-5futar5uv4ungb6bmnl3ejlco5oii97g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flInstaClone',
  );
}
